# k8s/base/mongodb/headless-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless-service # Descriptive name for the headless service
spec:
  # This makes the service "Headless."
  # DNS queries will return the IP addresses of the individual Pods.
  clusterIP: None

  # The selector must match the labels on the MongoDB StatefulSet's Pods
  selector:
    app: mongodb-stateful

  # The ports section defines how the service exposes the pods
  ports:
    # MongoDB's default port
    - port: 27017
      targetPort: 27017
      name: mongodb
